test_query:
    max_test_valid_distance_var: 0.02
    search_area_half_size: 4
    num_neighbor_gps: 8
    use_smallest: true
    compute_gradient: true  # whether to compute gradient
    compute_gradient_variance: true  # whether to compute gradient variance
    compute_covariance: false  # whether to compute covariance
    use_gp_covariance: false
    retrain_outdated: true  # whether to retrain the trained but outdated GPs
    use_global_buffer: true  # whether to use the global buffer for test queries
num_threads: 64
update_hz: 60
sensor_noise: 0.001
gp_sdf_area_scale: 4
max_valid_gradient_var: 0.1
invalid_position_var: 2.0
sdf_gp:
    sign_method: "kSignGp"  # "kSignGp"
    hybrid_sign_methods: [ "kNormalGp", "kExternal" ]
    hybrid_sign_threshold: 0.2
    normal_scale: 100.0
    softmin_temperature: 10.0
    sign_gp_offset_distance: 0.0 # -0.2, when it is 0.0, the sign GP relies on the gradients only
    edf_gp_offset_distance: 0.0
    sign_gp:
        kernel_type: erl::covariance::Matern32<float, 3>
        kernel_setting_type: erl::covariance::Covariance<float>::Setting
        kernel:
            x_dim: 3
            scale: 0.5
            scale_mix: 1
            weights: [ ]
        max_num_samples: 192   # max dataset size
        no_gradient_observation: false
    edf_gp:
        kernel_type: erl::covariance::Matern32<float, 3>
        kernel_setting_type: erl::covariance::Covariance<float>::Setting
        kernel:
            x_dim: 3
            scale: 0.3
            scale_mix: 1
            weights: [ ]
        log_lambda: 40
        max_num_samples: 192   # max dataset size
        no_gradient_observation: true
