valid_range_min: 0.2
valid_range_max: 30
angle_min: -3.1415927410125732
angle_max: 3.1415927410125732
num_rays: 360
discontinuity_detection: false
discontinuity_factor: 10
rolling_diff_discount: 0.9
min_partition_size: 5