test_query:
    default_invalid_sdf: -1
    max_test_valid_distance_var: 0.02
    search_area_half_size: 4
    num_neighbor_gps: 8
    use_smallest: true
    compute_gradient: true # whether to compute gradient
    compute_gradient_variance: false # whether to compute gradient variance
    compute_covariance: false # whether to compute covariance
    use_gp_covariance: false
    retrain_outdated: true # whether to retrain the trained but outdated GPs
    max_num_retrain_gps: 500 # max number of retrained GPs before a test query
    use_global_buffer: true # whether to use the global buffer for test queries
queue_priority:
    max_buf_outdated_count: 10000
    distance_weight: 0.05
    query_weight_for_loading: 0.1
    query_weight_for_retrain: 0.5
num_threads: 64
min_num_gps_to_update: 1024
new_gp_load_data_immediately: true
update_hz: 10 # minimum update frequency to maintain, it may be slower
sensor_noise: 0.001
gp_sdf_area_scale: 8 # should be large enough
max_valid_gradient_var: 0.1
invalid_position_var: 2.0
sdf_gp:
    sign_method: "external" # "sign_gp", "normal_gp", "external", "hybrid", "none"
    hybrid_sign_methods: [ "sign_gp", "external" ]
    hybrid_sign_threshold: 0.18 # > sqrt(3) * tree_resolution
    normal_scale: 1000.0
    softmin_temperature: 10.0
    sign_gp_offset_distance: -0.2 # <=0, when it is 0.0, the sign GP relies on the gradients only
    edf_gp_offset_distance: 0.0 # >=0, e.g. 0.015 will cause a shell of thickness 0.03 behind the surface
    sign_gp:
        kernel_type: erl::covariance::Matern32<float, 3>
        kernel_setting_type: erl::covariance::Covariance<float>::Setting
        kernel:
            x_dim: 3
            scale: 0.1
            scale_mix: 1
        max_num_samples: 48 # max dataset size
        no_gradient_observation: false
    edf_gp:
        kernel_type: erl::covariance::RadialBiasFunction<float, 3>
        kernel_setting_type: erl::covariance::Covariance<float>::Setting
        kernel:
            x_dim: 3
            scale: 0.043
            scale_mix: 1
        log_lambda: 25 # larger more accurate but less numerically stable
        duplicate_epsilon: 0.0
        use_exp_bias: true
        max_num_samples: 128 # max dataset size
        no_gradient_observation: true
