sdf_mapping_node:
    ros__parameters:
        surface_mapping_setting_type: erl::gp_sdf::BayesianHilbertSurfaceMapping<float, 2>::Setting
        surface_mapping_setting_file: config/template/bayesian_hilbert_mapping_2d_float.yaml
        surface_mapping_type: erl::gp_sdf::BayesianHilbertSurfaceMapping<float, 2>
        sdf_mapping_setting_file: erl_gp_sdf/config/template/sdf_mapping_2d_float.yaml
        use_odom: false
        odom_topic.path: /jackal_velocity_controller/odom
        odom_msg_type: transform_stamped # "odometry" or "transform_stamped"
        odom_queue_size: 200
        world_frame: map
        sensor_frame: front_laser
        scan_topic.path: /scan
        scan_type: laser # "laser", "point_cloud", or "depth"
        scan_frame_type: erl::geometry::LidarFrame2D<float>
        scan_frame_setting_file: config/sensors/lidar_frame_2d.yaml
        scan_stride: 1
        convert_scan_to_points: true
        scan_in_local_frame: false # converted to points in the world frame
        depth_scale: 0.001
        publish_tree: false
        publish_tree_binary: true
        publish_tree_frequency: 5.0
        tree_topic.path: surface_mapping_tree
        publish_surface_points: false
        publish_surface_points_frequency: 5.0
        surface_points_topic.path: surface_points
        update_time_topic.path: update_time
        query_time_topic.path: query_time
        sdf_query_service.path: sdf_query
        save_map_service.path: save_map
        load_map_service.path: load_map
