__base__: ../../common/sdf_mapping_float.yaml
test_query:
    max_test_valid_distance_var: 0.02
    search_area_half_size: 15
    num_neighbor_gps: 8
    max_num_retrain_gps: 200
update_hz: 10
min_num_gps_to_update: 256
gp_sdf_area_scale: 2
sdf_gp:
    sign_method: "external"
    edf_gp:
        kernel_type: erl::covariance::RadialBiasFunction<float, 3>
        kernel:
            x_dim: 3
        log_lambda: 200
        max_num_samples: 192 # max dataset size
