__base__: ../common/bayesian_hilbert_surf_mapping_float.yaml
local_bhm:
    bhm:
        min_distance: 0.9
        max_distance: 6.0
        sampling_area_scale: 2.5
        free_points_per_meter: 3
        init_mu: 5.0
        sparse_zero_threshold: 0.005
    kernel_type: erl::covariance::RadialBiasFunction<float, 3>
    kernel:
        x_dim: 3
        scale: 0.02
        scale_mix: 1
        weights: [ ]
    min_dataset_size: 30
    min_dataset_hit_size: 15
    max_dataset_size: 150
    hit_point_buffer_size: 256
    ray_buffer_size: 2048
    surface_grid_size: 7
ray_selector:
    azimuth_min: -3.141558
    azimuth_max: 3.141577
    elevation_min: -0.35
    elevation_max: 0.3848
    num_azimuth_angles: 1024
    num_elevation_angles: 32
    transform:
        - [ 1, 0, 0, 0 ]
        - [ 0, 1, 0, 0 ]
        - [ 0, 0, 1, 0 ]
tree:
    resolution: 0.1
    tree_depth: 10
    log_odd_min: -10
    log_odd_max: 100
    log_odd_hit: 0.85
    log_odd_miss: -0.3
    log_odd_occ_threshold: 10
update_map:
    method: 2
    max_update_dist: 4.0
    max_num_bhm: 1000
    max_num_voxels: 50000
filter_points: true
filter_points_min_z_world: -0.05
filter_points_max_z_world: 10.0
scaling: 1.0
bhm_depth: 9
hinged_grid_size: 7
bhm_test_margin: 0.03
